apiVersion: v1
kind: Pod
metadata:
  name: hello-sbhishek-pod
  labels:
    app: hello-abhishek-pod
spec:
  containers:
  - env:
    - name: MESSAGE
      value: Hi! I'm an environment variable created by Abhishek
    image: quay.io/practicalopenshift/hello-world
    imagePullPolicy: Always
    name: hello-world-override
    resources: {}
